myfirstdjangoproject1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import include, path

from . import views

app_name = 'recipes'  # Utilizar recipes:recipe, ao invés de recipes-recipe

urlpatterns = [
    path('', views.home, name='home'),
    path('recipe/category/<int:category_id>/', views.category, name="category"),
    path('recipe/<int:pk>/', views.recipe, name="recipe"),
]

recipes/models.py
from distutils.command.upload import upload
from email.policy import default

from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

# class Author(models.Model):
#     name = models.CharField(65)


class Recipe(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=165)
    slug = models.SlugField()  # campo indexado
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

recipes/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import get_list_or_404, get_object_or_404, render
from django.template.loader import render_to_string

# from utils.recipes.factory import make_recipe
from recipes.models import Recipe

# Create your views here.


def home(request):
    obj = {
        # 'recipes': [make_recipe() for _ in range(10)],
        'recipes': Recipe.objects.filter(is_published=True).order_by('-id')
    }
    return HttpResponse(render_to_string('recipes\\pages\\home.html', context=obj))


def category(request, category_id):
    # recipe = Recipe.objects.filter(
    #     category__id=category_id, is_published=True).order_by('-id')
    # if not recipe:
    #     # return render(request, 'recipes\\pages\\404.html', status=404)
    #     raise Http404('Error 404 - Categoria não encontrada')
    recipe = get_list_or_404(Recipe.objects.filter(
        category__id=category_id, is_published=True).order_by('-id'))
    return render(request, 'recipes\\pages\\categories.html', context={'recipes': recipe, 'title': f'{recipe[0].category.name}'})


def recipe(request, pk):
    print('id', pk)
    recipe = Recipe.objects.filter(id=pk, is_published=True).first()
    print('recipe', recipe)
    return render(request, 'recipes\\pages\\recipe.html', context={'recipe':recipe, 'is_detail_page': True})

recipes/templates/recipes/pages/categories.html
{% extends 'base/base.html' %}
{% block title %}{{title}}{% endblock title %}
{% block  content%}
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
        {%include 'recipes\\partials\\main-recipes.html'%}
    {% endfor %}
</div>
{% endblock %}

recipes/templates/recipes/pages/home.html
{% extends 'base/base.html'%}
{% block title %}Home{% endblock title %}
{% block  content%}
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
        {%include 'recipes\\partials\\main-recipes.html'%}
    {% endfor %}
</div>
{% endblock  %}

recipes/templates/recipes/pages/recipe.html
{% extends 'base/base.html'%}
{% block title %}{{recipe.author.first_name}}{% endblock title %}
{% block  content%}
<div class="main-content main-content-list container">
    <div class="main-content main-content-detail container">
        {%include 'recipes/partials/main-recipes.html'%}
    </div>
</div>
{% endblock  %}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
        <a href="https://www.google.com.br/" target="_blank" rel="noreferrer noopener">By Rodrigo Muniz</a>
    </div>

    <div class="powered">
        <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/fontawesome.min.css"
    integrity="sha512-r9kUVFtJ0e+8WIL8sjTUlHGbTLwlOClXhVqGgu4sb7ILdkBvM2uI+n/Fz3FN8u3VqJX7l9HLiXqXxkx2mZpkvQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/brands.min.css"
    integrity="sha512-rQgMaFKZKIoTKfYInSVMH1dSM68mmPYshaohG8pK17b+guRbSiMl9dDbd3Sd96voXZeGerRIFFr2ewIiusEUgg=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/solid.min.css"
    integrity="sha512-wQ0aDa8upf/3Fun6Qby6g8uXyPqKl54VpEO/SwjjqxeUwThb6TIP5kloJ2tOHqnjLsd88S5p1VoOIXEl42mHYg=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'global/css/global-style.css' %}">
    <link rel="stylesheet" href="{% static 'recipes/css/style.css' %}">
{% comment %}
<link rel="stylesheet" href="{% static 'recipes\\css\\style.css' %}">{% endcomment %}

recipes/templates/recipes/partials/header.html
{% comment %} {% load static %} {% endcomment %}
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a href="{% url 'recipes:home' %}" class="main-logo">
                <i class="fa-solid fa-book-open-reader main-logo-icon"></i>
                <span class="main-logo-name">Recipes</span>
                {% comment %} <img src="{% static 'global\imgs\img.jpg'%}" alt="alt"> {% endcomment %}
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/main-recipes.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href="{% url 'recipes:recipe' recipe.id %}">
            <img src="{{recipe.cover.url}}" alt="temporário">
        </a>
    </div>
    <div class="recipe-title-container">
        <a href="{% url 'recipes:recipe' recipe.id %}">
            <h2 class="recipe-title">{{recipe.title}}</h2>
        </a>
    </div>
    <div class="recipe-author">
        {%if recipe.author.first_name%}
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            {{recipe.author.first_name}} {{recipe.author.last_name}}
        </span>
        {% else %}
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            {{recipe.author.username}}
        </span>
        {%endif %}
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{recipe.created_at|date:"d-m-Y"}} às {{recipe.created_at|date:"H:i:s"}}
        </span>
        <span class="recipe-author-item">
            <a href="{%url 'recipes:category' recipe.category.id %}">
                <i class="fas fa-layer-group"></i>
                <span>{{recipe.category.name}}</span>
            </a>
        </span>
    </div>
    <div class="recipe-content">
        <p>{{recipe.description}}</p>
    </div>
    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title">
                <i class="fas fa-stopwatch"></i>
                {{recipe.preparation_time}}
            </h3>
            <div class="recipe-meta-text">
                {{recipe.preparation_time_unit}}
            </div>
        </div>
        <div class="recipe-meta recipe-savings">
            <h3 class="recipe-meta-title">
                <i class="fas fa-pizza-slice"></i>
                {{recipe.servings}}
            </h3>
            <div class="recipe-meta-text">
                {{recipe.servings_unit}}
            </div>
        </div>
    </div>
    {% if is_detail_page is not True %}
    <footer class="recipe-footer">
        <a href="{% url 'recipes:recipe' recipe.id %}" class="recipe-read-more button button-dark button-full-width">
            <i class="fas fa-eye"></i>
            <span>Veja mais...</span>
        </a>
    </footer>
    {% endif %}

    {% if is_detail_page is True %}
    <div class="preparation-steps">
        {{recipe.preparation_steps|linebreaksbr}}
    </div>
    {% endif %}
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="search-box container">
        <form action="" class="search-form">
            <input type="text" class="search-input" name="search">
            <button type="submit" class="search-button"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
    </div>
</div>